import crypto from 'node:crypto';

const PATH = 'data/crosswords.secure.json';
const REPO = 'enygmaticism/enygma';
const GITHUB_API = 'https://api.github.com';

function key() {
  const secret = process.env.ADMIN_PASSWORD || '';
  if (!secret) throw new Error('ADMIN_PASSWORD is not configured.');
  return crypto.createHash('sha256').update(`enygma-crosswords:${secret}`).digest();
}
function headers() { return { Accept:'application/vnd.github+json', Authorization:`Bearer ${process.env.GITHUB_TOKEN}`, 'X-GitHub-Api-Version':'2022-11-28' }; }
export function normalizeAnswer(value) { return String(value || '').toUpperCase().replace(/[^A-ZČĆŽŠĐ]/g,''); }
export function encryptCrosswords(data) { const iv=crypto.randomBytes(12); const cipher=crypto.createCipheriv('aes-256-gcm',key(),iv); const body=Buffer.concat([cipher.update(JSON.stringify(data),'utf8'),cipher.final()]); return Buffer.concat([iv,body,cipher.getAuthTag()]).toString('base64'); }
export function decryptCrosswords(ciphertext) { if(!ciphertext)return {}; const payload=Buffer.from(ciphertext,'base64'),iv=payload.subarray(0,12),tag=payload.subarray(payload.length-16),body=payload.subarray(12,payload.length-16); const decipher=crypto.createDecipheriv('aes-256-gcm',key(),iv); decipher.setAuthTag(tag); return JSON.parse(Buffer.concat([decipher.update(body),decipher.final()]).toString('utf8')); }
export async function readSecureCrosswords() { const r=await fetch(`${GITHUB_API}/repos/${REPO}/contents/${PATH}`,{headers:headers()}); if(r.status===404)return {data:{},sha:null}; if(!r.ok)throw new Error(`GitHub Crossword read failed: ${r.status}`); const b=await r.json(); const wrapper=JSON.parse(Buffer.from(b.content,'base64').toString('utf8')); return {data:wrapper.ciphertext?decryptCrosswords(wrapper.ciphertext):{},sha:b.sha}; }
export async function writeSecureCrosswords(data,sha,message) { const r=await fetch(`${GITHUB_API}/repos/${REPO}/contents/${PATH}`,{method:'PUT',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({message,content:Buffer.from(`${JSON.stringify(data,null,2)}\n`).toString('base64'),...(sha?{sha}:{})})}); if(!r.ok)throw new Error(`GitHub Crossword write failed: ${r.status}`); return r.json(); }
export function deriveEntries(grid,rows,cols) { const cells=Array.from({length:rows},(_,r)=>Array.from({length:cols},(_,c)=>grid[r][c]||'#')); const across=[],down=[]; let num=0; for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){ if(cells[r][c]==='#')continue; const startsAcross=c===0||cells[r][c-1]==='#'; const startsDown=r===0||cells[r-1][c]==='#'; if(startsAcross||startsDown)num++; if(startsAcross){let ans='';for(let x=c;x<cols&&cells[r][x]!=='#';x++)ans+=normalizeAnswer(cells[r][x]);if(ans.length>1)across.push({number:num,row:r,col:c,length:ans.length,answer:ans});} if(startsDown){let ans='';for(let y=r;y<rows&&cells[y][c]!=='#';y++)ans+=normalizeAnswer(cells[y][c]);if(ans.length>1)down.push({number:num,row:r,col:c,length:ans.length,answer:ans});} } return {across,down}; }
export function validateCrossword(input) { const rows=Number(input.rows),cols=Number(input.cols); if(!Number.isInteger(rows)||!Number.isInteger(cols)||rows<3||rows>25||cols<3||cols>25)return 'Grid must be between 3×3 and 25×25.'; if(!Array.isArray(input.grid)||input.grid.length!==rows||input.grid.some(row=>!Array.isArray(row)||row.length!==cols))return 'Grid dimensions are invalid.'; const grid=input.grid.map(row=>row.map(cell=>cell==='#'?'#':normalizeAnswer(cell).slice(0,1))); const {across,down}=deriveEntries(grid,rows,cols); if(!across.length&&!down.length)return 'The grid must contain at least one word.'; const clues=input.clues||{}; for(const e of [...across,...down]){const key=`${e.number}${across.includes(e)?'A':'D'}`;if(!String(clues[key]||'').trim())return `Missing clue for ${key}.`;if(e.length<2)return `Entry ${key} is too short.`;} return null; }
